apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-Cluster
  region: us-east-2

nodeGroups:
  - name: ManagedNodeGroup
    instanceType: m5.xlarge
    desiredCapacity: 3


cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]

